using OCCTProxy.Common;
using OCCTProxy.Common.Interfaces;
using OpenTK.Mathematics;
using System.Numerics;

namespace OCCT.Interfaces
{
    public interface IOCCTProxyInterface
    {
        bool ImGuiMouseUp(int btn, int x, int y);
        bool ImGuiMouseDown(int btn, int x, int y);
        void runOpenTk(IntPtr wnd, IntPtr glctx);
        bool InitViewer2(IntPtr glctx);
        void MouseMove(int x, int y);
        void cleanup();
        void Resize(int x, int y);
        void MouseDown(int btn, int x, int y);

        void MouseUp(int btn, int x, int y);
        void MouseScroll(int x, int y, int offset);
        void iterate();
        void StartRenderGui();
        void EndRenderGui();
        void ShowDemoWindow();
        void Begin(string str);
        bool Button(string str);
        bool Checkbox(string str, bool state);
        void Text(string str);
        int GetTotalShapes();
        void End();
        void StartZoomAtPoint(int theX1, int theY1);
        void ZoomAtPoint(int theX1, int theY1, int theX2, int theY2);
        Vector3d? GetGravityPoint();
        Vector3d? GetCenter();
        Vector3d? GetEye();
        Vector3d? GetUp();
        Matrix4? ProjectionMatrix();
        float? ProjectionScale();
        float? ProjectionFOVy();
        float? ProjectionAspect();
        float? ProjectionZNear();
        float? ProjectionZFar();
        int? ProjectionType();
        Matrix4? OrientationMatrix();
        void ResetSelectionMode();
        ManagedObjHandle Text2Brep(string str, double fontSize, double bevelHeight);
        void SetSelectionMode(SelectionModeEnum f);
        void TopView();
        void FrontView();
        ManagedObjHandle GetSelectedObject();
        List<ManagedObjHandle> GetSelectedObjects();
        List<ManagedObjHandle> GetDetectedVertices();
        ManagedObjHandle GetSelectedEdge();
        ManagedObjHandle GetDetectedObject();
        bool IsObjectSelected();
        void ShowStats(bool status);
        void SetDisplayMode(int m);
        void Display(IManagedObjHandle m, bool wireframe);
        void InitOCCTProxy();
        void RedrawView();
        void ShowCube();
        void ZoomAllView();
        List<IManagedObjHandle> ImportStep(string path);
        List<IManagedObjHandle> ImportStep(string path, List<byte> stream);
        List<IManagedObjHandle> ImportIges(string path);
        void LeftView();
        void ActivateGrid(bool enabled);
        void AxoView();
        void SetAutoViewerUpdate(bool v);
        IManagedObjHandle MakeFuse(IManagedObjHandle h1, IManagedObjHandle h2);
        IManagedObjHandle MakeDiff(IManagedObjHandle h1, IManagedObjHandle h2);
        IManagedObjHandle MakeCommon(IManagedObjHandle h1, IManagedObjHandle h2);
        void MoveObject(IManagedObjHandle h1, double x, double y, double z, bool rel);
        void MoveObject(ITopObjHandle h1, double x, double y, double z, bool rel);
        void RotateObject(IManagedObjHandle h1, double x, double y, double z, double rot, bool rel);
        void Erase(IManagedObjHandle h1, bool updateViewer = true);
        void Remove(IManagedObjHandle h1);
        void UpdateView();
        void UpdateCurrentViewer();
        void SetTransparency(IManagedObjHandle managedObjHandle, double v);
        IManagedObjHandle MakePrismFromFace(IManagedObjHandle managedObjHandle, double height);
        List<ISurfInfo> GetFacesInfo(IManagedObjHandle managedObjHandle);
        List<IEdgeInfo> GetEdgesInfo(IManagedObjHandle managedObjHandle);
        List<IVertInfo> GetVertsInfo(IManagedObjHandle managedObjHandle);
        void SetDefaultGradient();
        void BackView();
        void BottomView();
        void RightView();
        void SetColor(IManagedObjHandle h, int red, int green, int blue);
        List<double> GetObjectMatrixValues(IManagedObjHandle h);
        List<double> GetShapeMatrixValues(IManagedObjHandle h);
        void SetMatrixValues(IManagedObjHandle h, List<double> m);
        IManagedObjHandle MakeCone(double r1, double r2, double h);
        IManagedObjHandle MakeChamfer(IManagedObjHandle so, double r);
        IManagedObjHandle MakePrism(IManagedObjHandle managedObjHandle, double h);
        IManagedObjHandle Clone(IManagedObjHandle so);
        IManagedObjHandle MakeFillet(IManagedObjHandle so, double r);
        IManagedObjHandle MakeFillet2d(IManagedObjHandle so, double r);
        IManagedObjHandle HelixWire(double radius, double radius2, double pitch, double sweep);
        IManagedObjHandle MakePipe(IManagedObjHandle handle, double r);
        IManagedObjHandle Pipe(double x1, double y1, double z1, double x2, double y2, double z2, double size);
        IManagedObjHandle Sphere(double x1, double y1, double z1, double size);
        IManagedObjHandle MirrorObject(IManagedObjHandle handle, Vector3d dir, Vector3d pnt, bool axis2, bool rel);
        IManagedObjHandle MakeSphere(double r);
        IManagedObjHandle MakeCylinder(double r, double h);
        bool ExportStep(ITopObjHandle handle, string fileName);
        List<byte> ExportStepStream(ITopObjHandle handle);
        void MoveTo(int x, int y);
        void Pan(int x, int y);
        void Rotation(int x, int y);
        IManagedObjHandle MakeBox(double x, double y, double z, double w, double l, double h);
        void SetBackgroundColor(int r1, int g1, int b1, int r2, int g2, int b2);
        bool InitViewer(IntPtr handle);
        void SetMaterial(int v);
        void Zoom(int v1, int v2, int v3, int v4);
        IEdgeInfo GetEdgeInfoPosition(IManagedObjHandle obj);
        ISurfInfo GetFaceInfo(IManagedObjHandle obj);
        Vector3d? GetVertexPosition(IManagedObjHandle obj);
        void StartRotation(int x, int y);
        void Select(bool v);
        List<List<Vector3d>> IteratePoly(ITopObjHandle managedObjHandle, bool useLocalTransform = true, bool useWholeShapeTransform = true);
        void SetNextWindowSizeConstraints(int minx, int miny, int maxx, int maxy);

        IManagedObjHandle AddWireDraft(double height);
        IManagedObjHandle ImportBlueprint(Blueprint blueprint);
        IManagedObjHandle ImportBlueprint(Blueprint3d blueprint);

    }
}
